### ISSUE TITLE
No error about lack of the explicit extensions

### ISSUE THREAD

**Issue by Andarist** [arethetypeswrong/arethetypeswrong.github.io#24] opened 2023-05-07 23:10 UTC
This reports that everything is alright:
https://arethetypeswrong.github.io/?p=ts-pattern%404.2.4-test.0

but in reality this version of this package isn't quite consumable from ESM:
```
node_modules/ts-pattern/dist/index.d.ts:1:26 - error TS2834: Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

1 import * as Pattern from './patterns';
                           ~~~~~~~~~~~~

node_modules/ts-pattern/dist/index.d.ts:2:23 - error TS2834: Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

2 export { match } from './match';
                        ~~~~~~~~~

node_modules/ts-pattern/dist/index.d.ts:3:28 - error TS2834: Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

3 export { isMatching } from './is-matching';
```

**Comment by andrewbranch** [comment] 2023-05-08 04:23
Duplicate of #22

**Closed by andrewbranch** 2023-05-08 04:23 UTC
